@startuml

scale 2/3
'left to right direction
center header
    C4 Architecture: System Diagram Header
endheader

title Diagram Title <&circle-check>
'
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

'LAYOUT_WITH_LEGEND

Person(someuser, "Name", "Description")

System(systemtag, "Name", "Description")

System_Ext(externalsystemtag, "Name", "Description")

Rel_Neighbor(systemtag, externalsystemtag, "Neighbor Relationship Name", "Description")
Rel(someuser, systemtag, "Relationship Name", "Description")

center footer
    Diagram Footer $(Version)
endfooter
@enduml